### ISSUE TITLE
Shader variants

### ISSUE THREAD

**Issue by amerkoleci** [floooh/sokol-tools#10]
Hi,
Any idea if you plan to have shader variants or permutations support?

Vulkan SPIRV has specialization constants.

**Comment by breakin** [comment]
Clarification; If I have say a PBR-material with a lot of features and want to turn on/off uniforms/code etc based on usage, is the only way to do this now with sokol-shdc to run it multiple times and pretend it is different shaders?

**Comment by floooh** [comment]
@breakin running multiple times shouldn't be necessary I think, but you'd need to "stamp out" the shader variants manually.

I haven't played around with it yet, but I think the GLSL "frontend" fully supports #define and #ifdef. You could put the code that should be specialized into variations into common @block chunks, and inside this switch features on/off via #ifdef.

Then below, create @vs/@fs/@program variations by first "configuring" the next variation with #defines, and then @include_block the code blocks with the #ifdef (which would then be specialized by the #defines).

Something like this:
```glsl
@block vs_shared
#if FEATURE1
...
#endif 
#if FEATURE2
...
#endif 
@end

@block fs_shared
// ditto
@end

//--- variation 1
#define FEATURE1 (1)
#define FEATURE2 (0)
@vs vs_var1
@include_block vs_shared
@end 
@fs fs_var1
@include_block fs_shared
@end 
@program vs_var1 fs_var1

//--- variation 2
#define FEATURE1 (0)
#define FEATURE2 (1)
@vs vs_var2
@include_block vs_shared
@end 
@fs fs_var2
@include_block fs_shared
@end 
@program vs_var2 fs_var2
```
As I said, I haven't tried it yet, but it should work (and if it doesn't I should fix it :)

**Comment by breakin** [comment]
@floooh: Thanks for answering. Will test that and see how it works! It is a weird case where for some backends you want to precompile all variants but for GLSL it is just additional data taking space since compilation happens at runtime anyway. Probably ok either way but curious to see what happens!

**Comment by kochol** [comment]
I tested your solution but not work at all. The code inside #if is always ignored,

**Comment by kochol** [comment]
The #define directives must be inside @vs and @fs blcoks to work.

**Comment by eduardodoria** [comment]
Would be interesting to insert macros (#ifdef and #ifndef) in generated shader sources. Creating predefined variations is impossible with many variations like: uv, uv2, color, fog, morphtarget, skinning, clipping_planes, lighting, etc.
