### ISSUE TITLE
sokol-shdc: header-only output

### ISSUE THREAD

**Issue by code-disaster** [floooh/sokol-tools#12]
It may be handy to include generated headers from different source files, to have access to the constants and type definitions for uniform blocks.

This already works in the current version, but also causes the executable to embed multiple copies of the shader code.

Could be something like a `SHDC_IMPL` define, following the header-only library coding style.

**Comment by floooh** [comment]
Yes good idea, I wonder if it's better to reverse the check and instead have an SHDC_DECL to only include the declarations because it's more common to only include the generated headers once anyway?

**Comment by code-disaster** [comment]
Yes, good point.

**Comment by floooh** [comment]
fixed in https://github.com/floooh/sokol-tools/pull/13
