### ISSUE TITLE
Add a comma at the end of a storage buffer struct definition for odin generator

### ISSUE THREAD

**Issue by cr1sth0fer** [floooh/sokol-tools#132]
Since its simple, dont need a PR for it. 
Just need add a comma on this [line](https://github.com/floooh/sokol-tools/blob/master/src/shdc/generators/sokolodin.cc#L188)  ``` l_close("}},\n");``` to make odin compiler happy when using -strict-style and -vet flags

**Comment by floooh** [comment]
Ah thanks, that was an oversight (it's correct in the similar `gen_uniform_block_decl()` function.

The binaries in `sokol-tools-bin` will be uptodate when this CI pipeline goes green: https://github.com/floooh/sokol-tools/actions/runs/9646033758
