### ISSUE TITLE
undeclared identifier: 'backendGlcore'  (Sokol-Nim target lang)

### ISSUE THREAD

**Issue by crystalthoughts** [floooh/sokol-tools#140]
Hi - when generating gl nim code it gives me the error `undeclared identifier: 'backendGlcore'`. 
Is this a user error or a bug?

**Comment by floooh** [comment]
Are you on the latest version of the sokol-nim bindings? The sokol_gfx.h enum item `SG_BACKEND_GLCORE` was previously called `SG_BACKEND_GLCORE33`.

The change was in the storage buffer update in May 2024: https://github.com/floooh/sokol/blob/master/CHANGELOG.md#09-may-2024

**Comment by crystalthoughts** [comment]
I'll look into that later and confirm with you. Thanks

**Comment by crystalthoughts** [comment]
Works fine, thanks for your quick response :)
