### ISSUE TITLE
Changes in sg_shader_desc

### ISSUE THREAD

**Issue by dlannan** [floooh/sokol-tools#162]
I dont know if this is really a bug. More a query. 
I just recently updated all the sokol headers for luajit and now all my shader code no longer works mainly because of the changes in sg_shader_desc. 

The error Im getting is: 
```
[sg][error][id:128] .\sokol_gfx.h(16744): 
        VALIDATE_SHADERDESC_SOURCE: shader source code required

```
I think this is because Im not setting the source in the new structure correctly. 
Previously when I compiled the shader it would set the source using:
desc.vs.source = < blah >     
and 
desc.fs.source = < blah >

With the new desc, can I just move this to desc.vertex_func.source and desc.fragment_func.source?
Do I need to populate the whole sg_shader_function structure? 

And shouldnt the new compiler do some of this? I had a look at the output and it seems to be the same. Maybe Im missing some params or something? - No Ignore this comment. I think Im caching the built files. Will retest the compiler.

**Comment by dlannan** [comment]
Update with the new compiler. While compiling the cube-sapp.glsl shader I get:
```
./projects/examples/samples/cube-sapp.glsl:4:0: error: 'binding' : uniform/buffer blocks require layout(binding=X)
```
I think I need to update the samples etc? Here is an example of the compiler command in use:
```
\dev\luajit\Thunc\sokol-luajit\tools\shader_compiler\win32\sokol-shdc.exe -i ./projects/examples/samples/cube-sapp.glsl -o \dev\luajit\Thunc\sokol-luajit\bin\shaderbin\shader_gen.h -l glsl410 -f sokol
```
On Win 11 cli.
Will have a look to see what needs to be done.

**Comment by dlannan** [comment]
Ok. Can close this. I think I get the main changes needed. 
```
layout(binding = 0, std140) uniform....
````
And so on. Will update the shaders.

**Comment by floooh** [comment]
Yeah, check this changelog entry and the linked blogpost:

https://github.com/floooh/sokol/blob/master/CHANGELOG.md#07-nov-2024
