### ISSUE TITLE
support for file includes? (Reminder: docs)

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools#20]
As I'm using this tool, I'm getting to the point where it would make sense for me to have file includes. Is this something you have in your plan, or would you want to have a push request?

**Comment by floooh** [comment]
It's planned, but I didn't get around to do it (and it's not very high on my personal priority list), so a PR would be welcome :)

Quick brain dump of what I've been thinking so far:

- no 'header search path' via command line, instead the include paths would be relative to the cwd (allowing ../../.. etc), this is just to save some implementation work though.
- syntax: ```@include path```, not sure about whitespace, for simplicity I would disallow whitespace in the path, and don't have string delimiters (no " or ')
- ideally allow the @include everywhere in the including file (both inside and outside other @-blocks)
- the most work will be "flattening" the include tree while preserving filenames and line numbers, this means this simple string array here: https://github.com/floooh/sokol-tools/blob/f57e22f4a8406fa98c507ec37ff8f1803a233550/src/shdc/shdc.h#L219 needs to become an array of "line_t" structs, where line_t holds a filename, line number and the actual line string
- ...and at the other end of the pipeline, mapping shader compiler error messages back to the original file and line number needs to use this new information

...so it's not entirely trivial :)

**Comment by floooh** [comment]
...on further thought, having include paths relative to the cwd isn't a good idea... that would break the compilation if it's started from another directory, maybe passing in at least one "root header path" via command line makes the most sense..., even better would be multiple search paths of course, so it's compatible with typical compilers...

**Comment by mattiasljungstrom** [comment]
Ok, thanks for the brain dump, I'll take a look and see if I can sort it out.

**Comment by floooh** [comment]
...keeping the ticket open as reminder that I need to mention the new @include tag in the docs...

**Comment by floooh** [comment]
Ok, docs added, closing this issue.
