### ISSUE TITLE
Add a define in the generated code to get the implementation or not

### ISSUE THREAD

**Issue by rivten** [floooh/sokol-tools#22]
Like in most single-header library, you have to define an IMPLEMENTATION macro in order to get the full source code, otherwise you only get the header part.

This is useful in my use-case. My use case is that I'm currently trying out to use sokol_app and sokol_gfx in Zig and can't properly include the generated header in my zig code. Indeed, Zig does not properly parse the generated C file by itself. My solution would then be to compile the source with implementation and include the header-only part in the Zig code.

Maybe if it's bad to have everybody add the implementation-define-macro, this could be the other way around (#define SHDC_HEADER_ONLY before the include).

**Comment by floooh** [comment]
Yes, this was an oversight in the first version. There's a fix, but it's only partial.

Instead of an IMPLEMENTATION define to get the implementation, there's a ```SOKOL_SHDC_DECL``` check to *exclude* the implementation (so if SOKOL_SHDC_DECL is defined, you only get the declaration part, but not the implementation part.

However I'm currently seeing that there's one thing missing, a function prototype declaration for the ```xxx_decl()``` function. Let me know if you need this function prototype up in the declaration, it would be trivial to add :)

**Comment by rivten** [comment]
Yes basically I would need to import the xxx_desc() function in zig code, so the function prototype declaration would be needed.
Also, I'm no pro of static linking and that sort of stuff, but won't the "static" part of the function be problematic for compiling the implementation in on compile unit and using it in another ?

Thanks a lot for the very quick reaction though :)

**Comment by floooh** [comment]
> but won't the "static" part of the function be problematic for compiling the implementation in on compile unit and using it in another ?

Yes, with a separate function prototype in the declaration part, the "static inline" would go away and it would become a normal "externally visible" function.

**Comment by floooh** [comment]
This is fixed in https://github.com/floooh/sokol-tools/commit/03903d3b8116501dd154c4d37a77f1b38f6ad237, I haven't updated the executables in sokol-tools-bin yet though, will close this issue when that's done.

**Comment by floooh** [comment]
ok, executables in sokol-tools-bin have been updated

**Comment by floooh** [comment]
@rivten please note the updated behaviour described here: https://github.com/floooh/sokol-tools/issues/23#issuecomment-527493474

There's now a "proper" STB-style output format via ```--format sokol_impl``` where you define SOKOL_SHDC_IMPL to include the implementation.
