### ISSUE TITLE
SOKOL_SHDC_DECL should be SOKOL_SHDC_IMPL

### ISSUE THREAD

**Issue by floooh** [floooh/sokol-tools#23]
See discussion here: https://github.com/floooh/sokol-tools/commit/03903d3b8116501dd154c4d37a77f1b38f6ad237

While this requires changing existing code, I think in the long run it's better because it behaves the same as STB-style headers (while the current approach is the inverse and may be even more confusing).

**Comment by floooh** [comment]
...thinking further about this, a command line option to create a header/source pair would probably make sense...

**Comment by floooh** [comment]
here's how I'll do it:

- ```--format``` accepts *sokol*, *sokol_decl*, *sokol_impl* and *bare*
- *sokol* goes back to the original behaviour, there are no implementation or declaration guard-defines, all data is declared as ```static```, and all functions ```static inline```, there are no function prototypes in the declaration part
- *sokol_decl* uses the original behaviour with SOKOL_SHDC_DECL: no function prototype in the declaration part, all data is ```static```, all functions are ```static inlin```
- *sokol_impl* uses STB-style behaviour, a new SOKOL_SHDC_IMPL around the implementation part, the declaration has function prototypes, data is still static, but function implementation are not ```static inline```

I was toying with header/source pair too, problem with this is that the implementation needs to include sokol_gfx.h, but I don't want hardwired sokol-includes in the generated sources, so I dropped that idea.

**Comment by mattiasljungstrom** [comment]
Maybe merge the first two options, since option #1 is basically #2 without declaring SOKOL_SHDC_DECL?

Or remove sokol_decl and see sokol_impl as the updated approach? I don't know how many projects depends on this. One problem with SOKOL_SHDC_DECL is that I need to #undef it several places because it gets dragged in by header files.

**Comment by floooh** [comment]
>Maybe merge the first two options, since option #1 is basically #2 without declaring SOKOL_SHDC_DECL?

Hmm maybe, I thought it would be less confusing when the default (```sokol```) doesn't have any SOKOL_SHDC_DECL or _IMPL ifdefs)

I don't want to use ```sokol_impl``` as default either, because that requires the SOKOL_SHDC_IMPL define somewhere to be usable.

The default would basically always work without any defines, but one may end up with duplicate data in the build.

...this can then either be fixed with the ```sokol_decl``` or ```sokol_impl``` approach, whatever fits a specific scenario better.
