### ISSUE TITLE
Consider allowing the @blah special forms to be specified as a `#pragma` instead?

### ISSUE THREAD

**Issue by thomcc** [floooh/sokol-tools#24]
This allows the shaders to be processed by other naive tools, such as linters, editor plugins, etc. It wouldn't bother me if this were only allowed when passing a flag to shdc (I'd just always pass it). I'd be willing to implement this, if you'd accept the patch (it sounds easy).

**Comment by floooh** [comment]
I hadn't considered this but it's a good idea I think. I wouldn't put it behind a separate flag, since if those pragmas don't exist, everything will just work as before.

It'll be a bit until I get around to properly test and merge your PR though, but I think it's a good feature.

**Comment by floooh** [comment]
FYI: I had to rollback the binaries to the previous version. I'm getting a segfault on Linux (Ubuntu to be precise, haven't checked other versions), I'll need to investigate in the evening whether this is because of the source changes, or whether something has changed in the way I'm compiling the Linux exe in Docker.

**Comment by floooh** [comment]
...the crash only happens for the GLSL languages, so it's most likely unrelated to the #pragma sokol change. I'll properly debug this in the evening on my Linux dev laptop.

**Comment by floooh** [comment]
...ok, this was completely unrelated to the recent changes: it's a bug in SPIRV-Cross which only triggered in very recent GCC versions. Updating SPIRV-Cross to the latest version fixes it.

I'll recompile and commit the latest binaries now...

**Comment by thomcc** [comment]
Glad to hear it wasn't my fault!
