### ISSUE TITLE
bytecode generation for metal on macos not working?

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools#3]
Trying to generate metal shader with bytecode, but it seems to fail and only generate source code. Tested on the sample cube shader with:
./sokol-shdc --input cube-sapp.glsl --output cube-sapp.h --bytecode --slang metal_macos --dump

**Comment by floooh** [comment]
Yes, byte code generation isn't implemented yet both for Metal and D3D11. I wrote the docs as if it would be already implemented, but haven't mentioned anywhere that it isn't in yet, sorry :)

**Comment by floooh** [comment]
I've added a small note to the sokol-shdc docs that bytecode-generation isn't working yet. It's one of the next things I'll be doing though.

**Comment by mattiasljungstrom** [comment]
Thanks for a great tool!
