### ISSUE TITLE
Generated shader file gives 'initializing' errors on build.

### ISSUE THREAD

**Issue by deadwanderer** [floooh/sokol-tools#38]
I just updated sokol, sokol-tools, and sokol-samples to the latest version, and shader gen appears to be broken. An example of output from building texcube-sapp sample in sokol-samples:
`F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp.glsl.h(196,1): error C2078: too many initializers [F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp-ui.vcxproj]`

`F:\projects\sokol\sokol_gfx.h(1694,17): error C2078: too many initializers [F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp-ui.vcxproj]`

`F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp.glsl.h(150,1): warning C4047: 'initializing': 'const char *' differs in levels of indirection from 'int' [F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp-ui.vcxproj]`

`F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp.glsl.h(152,1): warning C4047: 'initializing': 'const char *' differs in levels of indirection from 'int' [F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp-ui.vcxproj]`

`F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp.glsl.h(152,1): warning C4047: 'initializing': 'const uint8_t *' differs in levels of indirection from 'int' [F:\projects\fips-build\sokol-samples\sapp-win64-vscode-debug\sapp\texcube-sapp-ui.vcxproj]`

**Comment by floooh** [comment]
Hi, this is most likely related to the commit eed168238eb91010d9613123984bdc1840fc287d in sokol_gfx.h (which added a new struct item to sg_shader_stage_desc, and the related changes in the sokol-shdc tool.

You basically need to update both things (sokol_gfx.h and the sokol-shdc binaries), and probably also run a "./fips clean" (if you're using fips) to delete any generated headers that might still be around.

Please let me know if this works.

I have rewritten the sg_shader_desc initialization in the code generated by sokol-shdc as part of those commits, which hopefully makes such changes (like adding new struct items to sg_shader_desc) less brittle in the future, so there may be some version range overlap between sokol_gfx.h and sokol-shdc.

I have attached texcube-sapp.glsl.h (see end of comment, built on Windows for the OpenGL backend) as example for what it should look with the latest sokol-shdc version (note how the ```texcube_shader_desc()``` function looks very different than before:

```
static inline const sg_shader_desc* texcube_shader_desc(void) {
  if (sg_query_backend() == SG_BACKEND_GLCORE33) {
    static sg_shader_desc desc;
    static bool valid;
    if (!valid) {
      valid = true;
      desc.attrs[0].name = "pos";
      desc.attrs[1].name = "color0";
      desc.attrs[2].name = "texcoord0";
      desc.vs.source = vs_source_glsl330;
      desc.vs.entry = "main";
      desc.vs.uniform_blocks[0].size = 64;
      desc.vs.uniform_blocks[0].uniforms[0].name = "vs_params";
      desc.vs.uniform_blocks[0].uniforms[0].type = SG_UNIFORMTYPE_FLOAT4;
      desc.vs.uniform_blocks[0].uniforms[0].array_count = 4;
      desc.fs.source = fs_source_glsl330;
      desc.fs.entry = "main";
      desc.fs.images[0].name = "tex";
      desc.fs.images[0].type = SG_IMAGETYPE_2D;
      desc.fs.images[0].sampler_type = SG_SAMPLERTYPE_FLOAT;
      desc.label = "texcube_shader";
    };
    return &desc;
  }
  return 0; /* can't happen */
}
```

If you can't resolve problem, please attach a copy of the texcube-sapp.glsl.h file you get as output from sokol-shdc (maybe I overlooked something when not compiling with the same command line options used in the sokol-samples reposotory.

[texcube-sapp.glsl.zip](https://github.com/floooh/sokol-tools/files/4842121/texcube-sapp.glsl.zip)

**Comment by floooh** [comment]
PS: one thing I totally forgot was bumping the version number here: 

https://github.com/floooh/sokol-tools-bin/blob/ad680aabcaed1af566f60c7294effa4e4acdd10a/fips-files/generators/SokolShader.py#L11

This would have triggered a rebuild of all code-generated headers without running an explicit ```fips clean```. I did this now, so if you just update sokol-tools-bin and run a built, the problem should also fix itself (without the fips clean).

**Comment by deadwanderer** [comment]
That did indeed resolve the issue. All working now (on your end; I still have my own bugs to fix! :-) )

Thank you for these fantastic libraries! They are such a joy to use!
