### ISSUE TITLE
Inconsistent SLOT_* binding index generation

### ISSUE THREAD

**Issue by fabiopolimeni** [floooh/sokol-tools#4]
First of all, thank you very much for providing this great tool!

I was transferring a toy sokol project of mine to use `shdc`, to forget about maintaining shaders for different platforms, while I encountered an inconsistency in the SLOT generation index. 

When I do define a fragment (maybe it also occurs on vertex stages too) uniform blocks and a uniform sampler, SLOTs definition happen to be progressively computed, producing sequential binding points (e.g. `SLOT_fs_uniforms=0` and `SLOT_tex=1`), where I think (and manually fixing the bindings confirms it) they should both start from 0.

I hope the following code clarifies further.

This extract of the fragment shader
```
@fs fs
uniform fs_params {
  vec4 ambient_spec;
};

uniform sampler2D albedo_tex;
...
```
generates `#define SLOT_albedo_tex 1`, while `#define SLOT_albedo_tex 0` is expected.  In fact, `sokol-gfx` complains that images binding points are not contiguous, and it asserts.

I've temporarily fixed this by explicitly setting the binding points:
```
@fs geo_fs
layout(binding=0) uniform fs_params {
  vec4 ambient_spec;
};

layout(binding=0) uniform sampler2D albedo_tex;
```
which generates 
```
#define SLOT_albedo_tex 0
#define SLOT_fs_params 0
```

Let me know if you can reproduce this issue on your side, and whether this is expected or a true bug.

I am on Win64/VS2017/GLCORE33.

Thanks again ;)

**Comment by floooh** [comment]
Hi, yes, that's definitely the wrong behaviour, the uniform block and texture bindings should be unrelated and both start at zero.

Looks like this is an unwanted side-effect of how glslang's "auto-map-bindings" feature works:

https://github.com/floooh/sokol-tools/blob/9183ba07da050eb57acd630c42edb7fc3e629858/src/shdc/spirv.cc#L171

I should be able to fix the bind locations myself later before in the SPIRV-Cross pass. I'll start working on a fix ASAP, until using ```layout(binding=xxx)``` is a good workaround.

**Comment by floooh** [comment]
Ok, this should be fixed in the source code now, but note that the precompiled exes in sokol-tools-bin haven't been updated yet.

**Comment by floooh** [comment]
...the executables with the fix have been updated now. I had to add another minor fix, my check whether an explicit binding was provided didn't work.
