### ISSUE TITLE
shdc: error message line index is off by one

### ISSUE THREAD

**Issue by code-disaster** [floooh/sokol-tools#41]
I noticed that the line numbers of error messages are off by one in the latest build.

My bisect attempts traced it back to the merge at 680f04b. Since I don't spot any relevant code changes on your side, I suspect a change/fix in one of the dependencies.

I guess this makes the adjustment at https://github.com/floooh/sokol-tools/blob/master/src/shdc/shdc.h#L170-L175 obsolete.

**Comment by floooh** [comment]
Whoops strange that I missed this. I'll have a look later today. Thanks for the bug report :)

**Comment by floooh** [comment]
Updated executables are not updated yet...

**Comment by floooh** [comment]
Ok exes are updated.
