### ISSUE TITLE
[SPIRVCross] Quiet compile errors for certain shaders with glsl100 as target

### ISSUE THREAD

**Issue by PeterHiber** [floooh/sokol-tools#48]
We have been using `sokol_shdc` for some time now and mostly it has worked fine. But lately (last 2-3 months) as we have started writing more and more complex shaders we have also encountered issues where certain shaders quietly fail to compile with no indication why.

It hasn't been super easy to pinpoint why or when it happens, it seems to be different things at different times. Sometimes it starts working again with minor changes. One thing we have noticed is that it mostly seem to be a problem when targeting `glsl100`. When removing that target some of these problem shaders compiles again.

Below is small shader that quietly fails to compile when targeting `glsl100`:

```
@vs VS
@glsl_options fixup_clipspace

in vec3 inPos;
in vec2 inTexcoord;
out vec2 texcoord;

void main()
{
	gl_Position = vec4(inPos.xyz, 1.0);
	texcoord = inTexcoord;
}
@end

@fs PS
in vec2 texcoord;
layout(location = 0) uniform sampler2D tex;
out vec4 fragColor;

uniform UniformBuffer0 {
	vec2 texSize;
};

void main()
{
	const uint NUM_SAMPLES_DIM = 4;
	const uint HALF_NUM_SAMPLES_DIM = 2;
	const vec2 offs = 1.0 / texSize;
	const vec2 baseCoord = texcoord + vec2(0.5f) - float(HALF_NUM_SAMPLES_DIM) * offs;

	vec4 sum = vec4(0.0);
	for (uint y = 0; y < NUM_SAMPLES_DIM; y++) {
		for (uint x = 0; x < NUM_SAMPLES_DIM; x++) {
			const vec2 sampleCoord = baseCoord + vec2(x, y) * offs;
			sum += texture(tex, sampleCoord);
		}
	}

	fragColor = sum / float(NUM_SAMPLES_DIM * NUM_SAMPLES_DIM);
}
@end

@program Repro VS PS
```

We are thankful for any help with this. :)

**Comment by floooh** [comment]
Hi, one potential source of such weird problems are the SPIRV-Tools optimizer passes. I've had various problems which sound similar to yours, doing little changes on shader source code would suddenly produce code that's no longer accepted by (in my case) WebGL shader compilers. I had to remove some optimizer passes to fix those problems, but other passes might trigger the same problem on code patterns I hadn't used yet.

You could try building sokol-shdc without calling this function:

https://github.com/floooh/sokol-tools/blob/e5c8ab164f4d577d643ecbd0d16ec16afaaeca04/src/shdc/spirv.cc#L101-L154

...and if this helps, we can figure out a better way to configure this. 

I'll try to look into the problem after the "big merge" this week. I think it's also time to do a dependency update, maybe bringing in new versions of SPIRVTools and SPIRVCross also helps a bit.

**Comment by PeterHiber** [comment]
Thanks for the quick reply!

We haven't tried shutting of the optimizer yet, but we might have discovered why `sokol-shdc` quietly exits with no message. The following code is in SpirV-Cross:

```
#ifdef NDEBUG
	(void)msg;
#else
	fprintf(stderr, "There was a compiler error: %s\n", msg.c_str());
#endif
```

Meaning you don't get the error message in SpirV-Cross is compiled in release builds. For the repro shader above the message is:

```
There was a compiler error: Unsigned integers are not supported on legacy targets.
```
I.e., just changing `uint` to `int` fixes it.

I don't know if this fixes all our issues, but getting proper error messages when something goes wrong should at least remove some of them. In any case, I don't have a simple repro shader to hand you anymore, so maybe this specific issue is resolved once the error message problem is fixed.

**Comment by floooh** [comment]
Ah ok, I wasn't aware of that (quite weird) SPIRVCross behavior. I'll try to look into this, if newer SPIRVCross version have the same behaviour I guess I'll write a ticket in the SPIRVCross project and see if I can come up with some sort of workaround in the meantime.

Thanks for investigating this issue!

**Comment by floooh** [comment]
FYI: this specific error (bool-to-uint on legacy target) should now be caught as a separate sokol-shdc error here:

https://github.com/floooh/sokol-tools/blob/48e57da1f46dc86182f1121193dd1dc9449a7b5c/src/shdc/spirvcross.cc#L96-L98

...which happens before SPIRVCross is called. But I'll see if I can do something about those silent errors in SPIRVCross too...
