### ISSUE TITLE
Metal Developer Tools for Windows 10

### ISSUE THREAD

**Issue by garettbass** [floooh/sokol-tools#49]
https://developer.apple.com/download/release/

In principle, this makes it possible to compile metal bytecode on windows.  Linking here because it was not easy to find.

**Comment by floooh** [comment]
Yep I've seen it, I think it wasn't quite as simple as I was hoping though, e.g the compiler hasn't been open sourced, it's basically binary blobs.

Also no Metal Developer Tools for Linux unfortunately (which would be more useful because of Docker'n'stuff).

**Comment by garettbass** [comment]
I will file this under, "maybe I will investigate some day when I really want the feature" 🤓
