### ISSUE TITLE
incorrect padding for uniform block with multiple vec3:s

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools#5]
Shader code example:
uniform fs_params {
    vec3 a;
    vec3 b;
    vec3 c;
};

Generates following struct:
typedef struct fs_params_t {
    glm::vec3 a;
    uint8_t _pad_12[4];
    glm::vec3 b;
    uint8_t _pad_24[8];
    glm::vec3 c;
    uint8_t _pad_36[12];
} fs_params_t;
(this asserts for incorrect size during sg_apply_uniforms)

But the correct struct should be: 
typedef struct fs_params_t {
    glm::vec3 a;
    uint8_t _pad_12[4];
    glm::vec3 b;
    uint8_t _pad_24[4];
    glm::vec3 c;
    uint8_t _pad_36[4];
} fs_params_t;

If I change it manually, code works. :)

(Tested on VS2017, Win10)

**Comment by floooh** [comment]
Whoops, that's an obvious bug, thanks for catching that :)

**Comment by floooh** [comment]
...note: bug is fixed in source but binaries haven't been updated yet.

**Comment by floooh** [comment]
...ok executables in sokol-tools-bin have been updated with the fix.
