### ISSUE TITLE
error "highp: overloaded functions must have the same parameter precision qualifiers"

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools#50]
After latest update to sokol-tools, one of my shaders doesn't compile anymore, the error is a bit cryptic:

> error: 'highp' : overloaded functions must have the same parameter precision qualifiers for argument 1
> error: 'highp' : overloaded functions must have the same parameter precision qualifiers for argument 2
> error: 'highp' : overloaded functions must have the same parameter precision qualifiers for argument 3
 
I've narrowed it down to the max3 function in this minimal test case below. I'm not sure exactly what's going on but it happens on all platforms, so I assume it has to do with early convertion/parsing somehow.

I compile the shader below on the cmd line with the following parameters:
> sokol-shdc --input shader.glsl --output shader.glsl.h --slang hlsl5 --genver 4 --errfmt msvc --format sokol --bytecode

(The error happens both on macOS and Win10 versions.)

```
// vertex shader
@vs vs
layout(location=0) in vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0., 1.);
}
@end

// fragment shader
@fs fs
out vec4 out_color;

// bad function
float max3(float a, float b, float c)
{
    return max(max(a, b), c);
}

void main() {
    out_color = vec4(1);
}
@end

@program program1 vs fs
```

**Comment by mattiasljungstrom** [comment]
Turns out it was the function name, changing it to my_max3() works.

**Comment by mattiasljungstrom** [comment]
max3 isn't a defined function in either GLSL, but it looks like SPIRV is supporting some kind of extension:
https://github.com/KhronosGroup/SPIRV-Cross/blob/401af493263d5b45f2bf993f0d6ddc7dc850cd52/shaders/amd/shader_trinary_minmax.comp

**Comment by floooh** [comment]
Hmm ok, I wonder if it's related to this change:

https://github.com/floooh/sokol-tools/commit/e5c8ab164f4d577d643ecbd0d16ec16afaaeca04

I've switched the "client convention" for the initial compile pass to Vulkan from OpenGL, because that catches any "freestanding" uniforms outside uniform block structs as errors (as it should be).

**Comment by mattiasljungstrom** [comment]
Interesting, would be interesting to know what other things differ from Vulkan mode GLSL, and plain GLSL. Is there an overview doc somewhere? Couldn't find anything in my quick searches.

**Comment by floooh** [comment]
I don't know the exact differences either unfortunately. Only that I had to use "Vulkan mode" when compiling GLSL to "WebGPU SPIRV", but thise special case is now the normal case.

**Comment by mattiasljungstrom** [comment]
It looks like this is a list of all available operations:
https://github.com/KhronosGroup/glslang/blob/ffccefddfd9a02ec0c0b6dd04ef5e1042279c97f/glslang/Include/intermediate.h

And the language is defined here (?):
https://github.com/KhronosGroup/glslang/blob/ffccefddfd9a02ec0c0b6dd04ef5e1042279c97f/glslang/MachineIndependent/glslang.m4

I'll close this ticket, since this is an issue with SPIRV. If you try to call max3() without defining the extension, you get an error. But at the same time it's not possible to define your own version.

**Comment by zeromake** [comment]
@floooh 
`transpose` fun name has same problem

```glsl
mat3 transpose(mat3 mat) {
    vec3 i0 = mat[0];
    vec3 i1 = mat[1];
    vec3 i2 = mat[2];

    return mat3(
        vec3(i0.x, i1.x, i2.x),
        vec3(i0.y, i1.y, i2.y),
        vec3(i0.z, i1.z, i2.z)
    );
}
```

```
error: 'highp' : overloaded functions must have the same parameter precision qualifiers for argument 1
```
change to `my_transpose` is normal
