### ISSUE TITLE
Prefix SLOT defines with shader name

### ISSUE THREAD

**Issue by edubart** [floooh/sokol-tools#52]
When I generate shader headers, in case the sampler name or uniform name has the same name as other shader, then SLOT macros gets defined twice.

For example in `shader_a.glsl` and `shader_b.gsls` I've :
```c
uniform sampler2D iChannel0;
uniform fs_uniform {
    float iLevel;
};
```

Then both `shader_a.glsl.h` and `shader_b.glsl.h` generates :
```c
#define SLOT_iChannel0 (0)
#define SLOT_fs_uniform (0)
```

This means if I include both headers within the same file then `SLOT_iChannel0` and `SLOT_fs_uniform` will get defined twice.

## Workaround
One workaround is to use a unique name for sampler and uniform block for each shader, I see no problem for for the `fs_uniform` case as it doesn't impact GLSL code, but for sampler names requires using unique names for each texture sampler for each shader, which is inconvenient.

## Possible solution
I wish those `SLOT` macros were prefixed with shader name, like the `ATTR` macros already are.

**Comment by floooh** [comment]
The intended way to resolve such name collisions is the ```@module``` keyword (which essentially defines per-input-file namespace:

https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md#module-name

This also affects the generated SLOT defines. Would that work for you?

**Comment by edubart** [comment]
> The intended way to resolve such name collisions is the `@module` keyword (which essentially defines per-input-file namespace:
> 
> https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md#module-name
> 
> This also affects the generated SLOT defines. Would that work for you?
That will work great! Sorry I missed that in the docs.
