### ISSUE TITLE
uniform block members are optimized away

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools#63]
The latest binary seems to perform more aggressive optimizations on the shader code. It optimizes away unused members of uniform blocks, which means that bindings will not match anymore. Is there a flag somewhere to turn this off? Any idea where I should start looking?

My own code is a bit complex, if needed I will try to provide a simple example later.

**Comment by mattiasljungstrom** [comment]
No, they are generated correctly in C, but what happens is that shaders that shared the same input block now need different names, even though the final C uniform structs look exactly the same. I believe what changed is in the spirv optimization, but I wonder if perhaps uniform_block_t::equals() is too strict? I didn't have time to debug this further. Here is a simple example of failure:

```
@vs vs_test
layout(location=0) in vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0., 1.);
}
@end

@fs fs_test1
out vec4 out_color;
layout(binding = 0) uniform fs_block_test {
    vec4 u_color4;
    float u_a1;
};
void main() {
    out_color = u_color4;
}
@end

@fs fs_test2
out vec4 out_color;
layout(binding = 0) uniform fs_block_test2 {
    vec4 u_color4;
    float u_a1;
};
void main() {
    // out_color = vec4(u_a1);              // works
    out_color = vec4(1) * u_a1;             // doesn't work
}
@end

@program test1 vs_test fs_test1
@program test2 vs_test fs_test2
```

Error: "conflicting uniform block definitions found for ..."

**Comment by mattiasljungstrom** [comment]
Did some more testing on what works and doesn't work, and it's quite random tbh:

```
@vs vs_test
layout(location=0) in vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0., 1.);
}
@end

@fs fs_test1
out vec4 out_color;
layout(binding = 0) uniform fs_block_test {
    vec4 u_color1;
    vec4 u_color2;
};
void main() {
    out_color = u_color1 * 0.5 + u_color2 * 0.5;
}
@end

@fs fs_test2
out vec4 out_color;
layout(binding = 0) uniform fs_block_test {
    vec4 u_color1;
    vec4 u_color2;
};
void main() {
    // out_color = u_color1;                            // works
    // out_color = u_color1 + u_color2;                 // works
    // out_color = u_color1 * 0.9 + u_color2 * 0.5;     // works

    out_color = 0.9 * u_color1 + u_color2;              // doesn't work
    // out_color = vec4(1) * u_color1;                  // doesn't work
    // out_color = vec4(1) * u_color1 + u_color2;       // doesn't work
}
@end

@program test1 vs_test fs_test1
@program test2 vs_test fs_test2
```

**Comment by floooh** [comment]
> No, they are generated correctly in C, but what happens is that shaders that shared the same input block now need different names

Ah alright, makes sense. I'll try to find a solution first where the uniform block isn't 'unshared', because I think it's better if different shaders that (are supposed to) use a shared uniform block can still use the same common C struct.

For a slightly related problem, I had also added the optional reflection functions which allows to check if a uniform block member exists and what its offset is, this is used in the shader-features sample (https://github.com/floooh/sokol-samples/blob/master/sapp/shdfeatures-sapp.c), but it's also much more complicated to use versus just accessing a C struct member.

**Comment by floooh** [comment]
PS: here's also something interesting, somehow I had a hunch that the new optimization could be a problem and created this test shader:

```glsl

@block shared
uniform params {
    mat4 mvp;
    float bla;
};
@end

@vs vs1
@include_block shared
in vec4 position;
out vec4 color;
void main() {
    gl_Position = position * mvp;
    color = vec4(bla, bla, bla, 1.0);
}
@end

@vs vs2
uniform xxx {
    float blub;
};
@include_block shared
in vec4 position;
out vec4 color;
void main() {
    gl_Position = position * mvp;
    color = vec4(1.0, 1.0, blub, 1.0);
}
@end

@fs fs
in vec4 color;
out vec4 fragColor;
void main() {
    fragColor = color;
}
@end

@program p1 vs1 fs
@program p2 vs2 fs
````

The first vertex shader uses ```bla```, but the second doesn't, and I would have expected that the uniform ```bla`` is removed in the second vertex shader, but it wasn't (unless I made some stupid error).

Anyway, I'll look into this stuff now.

**Comment by floooh** [comment]
I think your suspicion was right that the uniform-block equals test is too strict now. I had to add a new "instance name" in the uniform block for the mixed-type uniform block type stuff, and testing this struct-instance-name in the equals() function doesn't make much sense:

https://github.com/floooh/sokol-tools/blob/56ab78d4bee227818ff8488006c0e7fe8af2c5c2/src/shdc/shdc.h#L432

With that test removed both your shaders compile now without error. I'll commit that fix and then build new executables. Will close the ticket after the exes are updated (feel free to re-open if there's still something wrong).

**Comment by floooh** [comment]
Ok, exes are all updated (next thing I'll do as automate this via GH Actions).

**Comment by mattiasljungstrom** [comment]
Yes, looks like it's working now for me too. Thanks for the quick fix!
