### ISSUE TITLE
excessive use of library dependencies

### ISSUE THREAD

**Issue by rofl0r** [floooh/sokol-tools#66]
i was trying to compile your v6502r perfect z80 simulator, and to my utmost surprise your fips build system fetched and executed *binary* sokol-tools. this is not acceptable for a build from source distro so i instead tried to build this repo, which is exceedingly difficult due to the use of all its micro-dependencies.
even more frustrating is that fmt subrepo fails to build because it requires a bleeding edge C++ compiler:

```
~/tmp/v6502r[master]$ make
g++  -Iext/asmx/src -Isokol -DASMX_Z80  -c -o sokol-tools/ext/fmt/src/fmt.o sokol-tools/ext/fmt/src/fmt.cc
sokol-tools/ext/fmt/src/fmt.cc:3:4: error: #error Module not supported.
 #  error Module not supported.
    ^~~~~
sokol-tools/ext/fmt/src/fmt.cc:40:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
make: *** [sokol-tools/ext/fmt/src/fmt.o] Error 1
```

**Comment by floooh** [comment]
Well, yeah, that's why the prebuilt executables exist, because it's so painful to build with all those massively complex C++ dependencies (and it will take 10..20 minutes to build, except you're on a machine with a lot of CPU cores).

You can build the shader compiler via fips yourself, in that case, no prebuilt executables are used. You still need a somewhat recent compiler though. Build instructions are here:

https://github.com/floooh/sokol-tools#howto-clone-build-run-and-debug

If you want to write your own build system files (e.g. not use fips), you can check the build.zig file here (https://github.com/floooh/sokol-tools/blob/master/build.zig), this should be easier to translate to another build system than the fips+cmake files.

**Comment by floooh** [comment]
PS: Integrating a prebuilt header file is actually a good idea. I didn't expect that too many people would actually *build* the tool themselves, instead of using the hosted WASM versions.

**Comment by rofl0r** [comment]
thanks for the tips. in my case i'm hosting a build-from-source distro, so everything needed must be built from source. i also support non-mainstream architectures like mips or powerpc.
anyway, maybe you could consider using snprintf() instead of "fmt" and implementing your own 15-line string::split() function instead of using pystring. this would already get rid of 2 dependencies, including the only one that can't be built without a C++17 compiler.
every dependency comes with a cost for the user, even if it's hidden behind a build system with [micro-dependency management](https://drewdevault.com/2021/11/16/Cash-for-leftpad.html) such as fips.

**Comment by floooh** [comment]
Pystring and fmt are both very simple dependencies (and they are both *extremely* helpful compared to what's available in the C++ stdlib). The actually problematic dependencies are SPIRVTools, SPIRVCross and glslang, which are all very big and complex C++ dependencies. And soon-ish, Tint will be added for WebGPU/WGSL support, and this requires C++17 anyway (as far as I'm aware the other dependencies only require C++11: https://github.com/floooh/sokol-tools/blob/05f016ef654d133d1b82ec6437c9fc519e876d23/CMakeLists.txt#L5).

The sokol-shdc dependencies are integrated as git submodules btw, not via fips: https://github.com/floooh/sokol-tools/tree/master/ext

**Comment by rofl0r** [comment]
> Pystring and fmt are both very simple dependencies 

simple or not, at least fmt raises the bar to C++17

> (and they are both extremely helpful compared to what's available in the C++ stdlib).

the solution is not to use C++, obviously, but you're a windows user so you've been subject to 30 years of m$ propaganda in contra of C and pro C++, so it's unlikely that pointing this out will change your mind...

> The actually problematic dependencies are SPIRVTools, SPIRVCross and glslang, which are all very big and complex C++ dependencies.

from what i can see there's almost no way around them, and they're not as problematic as fmt in that they don't enforce a C++ standard that's newer than the last LTS release of a typical linux distro.

> The sokol-shdc dependencies are integrated as git submodules btw, not via fips: 

yes, i've noticed. but it's the same concept in the end.

**Comment by floooh** [comment]
> simple or not, at least fmt raises the bar to C++17

As I wrote elsewhere, C++11 should do. C++17 will only be needed once the Tint branch for WGSL support will be merged to master.

> but you're a windows user so you've been subject to 30 years of m$ propaganda...

Lol, for coding I'm actually mostly on macOS, with the remaining time equally split between Linux and Windows.

**Comment by rofl0r** [comment]
ok, if you really want to support C++11 then you should set the submodule version of fmt to d3c523e0 (11 months ago), which is the last version that doesn't use [C++ 20 modules](https://gcc.gnu.org/projects/cxx-status.html) - you can see on that page when support for the cpp macro `__cpp_modules` was added (tl;dr - it requires gcc 11 or newer).
