### ISSUE TITLE
Using 'infinity' leads to invalid C header

### ISSUE THREAD

**Issue by DctrNoob** [floooh/sokol-tools#76]
I sometimes want to initialize a shader variable with infinity because I want to keep track of a minimum in a loop. I define infinity as I would in GLSL via `const float INF = 1.0 / 0.0` which is afaik the common way to do it (see e.g. https://stackoverflow.com/questions/10435253/glsl-infinity-constant).

However, when doing it this way in a shader to be compiled by SHDC to a concrete shading language (in my case: Metal), the generated C header leads to compilation errors due to nested comment blocks in the commented intermediate code:
`
/*
[...]
    #line 986 [...]
        float d = as_type<float>(0x7f800000u /* inf */);
*/
`

So the intermediate code contains the comment block `/* inf */` within an existing comment block and the C/C++ compiler doesn't like that. So this prevents me from using infinity as I used to (which maybe wrong; I'm happy to be corrected).

**Comment by floooh** [comment]
Oh, interesting. Looks like this comment is injected by SPIRVCross. I guess the easiest solution is to replace the /* and */ with something else right before writing the comment blocks in the code generator output. I'll see if I can fix it right away.

**Comment by floooh** [comment]
...ok looks like this now:

```cpp
out.color = in.color0 * as_type<float>(0x7f800000u /_ inf _/);
```

I'll commit the fix and start a new GH Actions build to update the executables in sokol-tools-bin.

**Comment by floooh** [comment]
When this is finished you can give it a whirl: https://github.com/floooh/sokol-tools/actions/runs/2650629631

**Comment by DctrNoob** [comment]
Thanks @floooh! Worked like a charm.
