### ISSUE TITLE
Vertex Shader uniforms in Metal

### ISSUE THREAD

**Issue by timeinpixels** [floooh/sokol-tools#78]
Hi,

I am just trying to do something simple in vertex shader by passing an extra value through uniforms and this is what I get in generated shader:

`vertex main0_out main0(main0_in in [[stage_in]], constant vs_params& _38 [[buffer(0)]], ...`

Is this correct? When I try to set the buffers I use index 0 for [[stage_in]] but then the uniform buffer index is also 0...
Am I reading this correctly or this should be done differently?

Thanks in advance!

**Comment by timeinpixels** [comment]
Oh! I totally missed that. And then we set the buffer index in vertex attributes. Makes sense now 😁
Thanks for the speedy explanation!

**Comment by floooh** [comment]
Yes the last missing piece is setting the correct buffer slot index in the MTLVertexDescriptor, which must also be offset by SG_MAX_SHADERSTAGE_UBS, this happens here:

https://github.com/floooh/sokol/blob/01eeb35658fee9b6fe2e31145925fbd5e22faf47/sokol_gfx.h#L10887
