### ISSUE TITLE
Add support for mat3 in uniforms

### ISSUE THREAD

**Issue by DagAgren** [floooh/sokol-tools#79]
It seems mat3 in uniforms outputs INVALID_UNIFORM_TYPE on the C side. Could support be added for this? And possibly other matrix sizes?

**Comment by floooh** [comment]
Yes, as far as I remember, mat3 had the same memory packing rules as an array of vec3, and the internal alignment for array items that are not a multiple of 16 bytes differs between 3D backends.

You need to put 3 individual vec3 into your uniform data, and then load the mat3 in the shader from those individual vec3, for instance: ```mat3 m3 = mat3(mx, my, mz)```

There's some info about uniform data memory layout here:

https://github.com/floooh/sokol/blob/7244adc9d72d7a3ac6480a31c3d3573adfe3f913/sokol_gfx.h#L345-L451

Maybe once OpenGL can be kicked out those rules can be relaxed. That will be a while though.
