### ISSUE TITLE
Dawn WebGPU Location decoration must not be applied to this storage class

### ISSUE THREAD

**Issue by xReveres** [floooh/sokol-tools#83]
I tried to compile imgui.glsl from `test/imgui.glsl` to load in Dawn WebGPU but crashes:
```
Parser: error: line:29: [VUID-StandaloneSpirv-Location-06672] Location decoration must not be applied to this storage class
  %tex = OpVariable %_ptr_UniformConstant_13 UniformConstant
```

**Comment by floooh** [comment]
The WebGPU stuff in the main branch is waaayyy outdated, please don't use it :)

There's a somewhat more recent branch, but this is also most likely outdated by now: https://github.com/floooh/sokol-tools/tree/tint-integration

I plan to finish the WebGPU support "sometime later this year" once WebGPU 1.0 is really finalized and shipping.

**Comment by xReveres** [comment]
I can't wait. Thanks for explanation.

**Comment by xReveres** [comment]
I tried to compile (using glslang) on my own and I discovered following function in `glslang::TShader`:
```
shader.setTextureSamplerTransformMode(EShTexSampTransUpgradeTextureRemoveSampler);
```
With this method my fragment shader:
```glsl
#version 450 core
layout(binding=0) uniform texture2D tex;
layout(binding=1) uniform sampler smp;

layout(location=0) in vec2 uv;
layout(location=1) in vec4 color;

layout(location=0) out vec4 frag_color;
void main() {
    frag_color = texture(sampler2D(tex,smp), uv) * color;
}
```
Is cross translated to:
```glsl
#version 300 es
#extension GL_GOOGLE_cpp_style_line_directive : require
precision mediump float;
precision highp int;

uniform highp sampler2D tex;

layout(location = 0) out highp vec4 frag_color;
in highp vec2 uv;
in highp vec4 color;

#line 10 ""
void main()
{
#line 10 ""
    frag_color = texture(tex, uv) * color;
}
```
P.S. "I plan to finish the WebGPU support "sometime later this year" once WebGPU 1.0 is really finalized and shipping."
In Chrome 113 (~Apr 26), WebGPU will be enabled by default. So I think the standard will not change at all.
